python main.py \
    --data data_personal/ \
    --emsize 32 \
    --nhid 128 \
    --nlayers 2 \
    --lr 5e-5 \
    --wdecay 1e-5 \
    --epochs 10 \
    --batch_size 128 \
    --dropout 0.1 \
    --output exp/ \
    --logfile exp/log.txt
